S2-group/android-runner

ExperimentRunner/MonkeyRunner.py
ExperimentRunner/Scripts.py

I found `MonkeyReplay` unnecessarily complicated, so I implemented a simpler way of running MonkeyRunner scripts called just `MonkeyRunner`.
From the docstring of `MonkeyRunner`:
> As opposed to `MonkeyReplay`, it runs the scripts directly using MonkeyRunner.
Thanks to that it's not necessary to go through a layer of indirection in the
form of JSON files and a custom runner. This results in higher flexibility and
greater control.
>
> Usage:
1. Create a script runnable by MonkeyRunner.
2. Add it to the config file with the type "monkeyrunner".
>
> Important!
> The script has to be directly runnable by MonkeyRunner. It means that:
- it has to create an instance of `MonkeyDevice` explicitly in the script,
- all operations are supposed to be invoked on this instance,
- there has to be …

Implement support for running vanilla MonkeyRunner scripts

---

ExperimentRunner/Plugins/Batterystats.py

line 24: self.paths.CONFIG_DIR is wrong because you cannot access to a dictionary attribute like that, correct syntax is self.paths["CONFIG_DIR"]
line 65: we tried the command produced there (systrace with its parameters) but when you try to open the report file generated it return an error about the system clock; finally, deleting from the command string the -b parameter (buffer) it goes well
line 100: the "open mode" of the file must be w+
line 130: rows = self.aggregate(data_dir) -> aggregate procedure doesn't exist, we presume that the correct one is aggregate_final
line 146 (the tough one): at line 154 reduce doesn't accept an empty set(runs), so we inizialized runs_total before like a dir() and reduce only if run is not empty.
Moreover at line 148 run_file.contains('Joule') is wrong …

Some fixes about BatteryStats.py

---

__main__.py

Defining a new variable within the paths folder which should keep track of the directory AND filename of the config file.  This path variable will be used in batterystats.py in order to reload the file to fetch the required information.

Defining new Path Variable

---

AndroidRunner/Adb.py
AndroidRunner/Experiment.py
AndroidRunner/Progress.py
AndroidRunner/Tests.py
README.md
examples/batterystats/config.json
examples/batterystats/config_web.json
examples/native/config.json
examples/native/config_android.json
examples/performance/config.json
examples/plugin/config.json
examples/web/config.json
examples/web/config_root_charging_disabled.json
tests/unit/fixtures/test_config.json
tests/unit/fixtures/test_progress.xml
tests/unit/test_devices.py
tests/unit/test_experiment.py
tests/unit/test_progress.py
tests/unit/test_utils.py

This PR adds the option to restart adb after each run.  Depending on the machine, using this option might require that the end user execute the experiment as a privileged user to prevent adb authorization problems.  I added a method in Tests.py that will confirm that the user inputted command in config.json matches the available options for that field located in Experiment.py.  Also included are updates to tests/unit/test_experiment.py, test_utils.py and test_devices.py.
Note 1: The calls to time.sleep in Adb.cleanup are necessary to avoid aggregation errors like IndexOutofRange.  I bumped up the seconds for insurance.
Note 2: The time to run test_devices.py increased by 15 seconds, since there are a total of 15 sleep seconds in adb_cleanup.
Other changes include spelling and grammatical …

Adb cleanup

---

README.md

When I was setting up my experiment I copied the attribute name fro the description.
Since there was a typo, the attribute was being ignored.
After double-checking in the README, I verified that there was a typo in the attribute description.

Fixes a typo when describing the `devices_spec` attribute in README

---

AndroidRunner/Experiment.py

The last task before waiting X seconds between runs is collecting results.
If something occurs in this task without triggering an exception (e.g., the computation froze), we won't know.
This can be particularly confusing for researches and students not familiar with AR.
Sure, we can check the log file and verify the sleeping statement there, but it would be nice to have this statement also printed in the console UI.

Inform in the console UI when the waiting time between runs start

---

AndroidRunner/Plugins/android/Android.py

The Android profiler never clears up the collected data points.
Therefore, each run contains the data points collected in all runs prior to this run.
This commit ensures that the data points are reset before starting profiling.
Since the timer-based profiling can trigger one additional profiling after executing the `stop_profiling` method, it is safer to clear the data points array before starting the profiling.
Run number 1
```
datetime,cpu,mem
Fri Aug 28 14:14:28 GMT 2020,0.9,76682
Fri Aug 28 14:14:28 GMT 2020,0.9,76393
Fri Aug 28 14:14:29 GMT 2020,0.9,76417
Fri Aug 28 14:14:29 GMT 2020,0.9,76417
Fri Aug 28 14:14:29 GMT 2020,0.9,76417
Fri Aug 28 14:14:30 GMT 2020,0.9,76417
Fri Aug 28 14:14:30 GMT 2020,0.9,76425
Fri Aug 28 14:14:30 GMT 2020,0.9,76425
Fri Aug 28 14:14:31 GMT …
```

Clear up the Android profiler data points from the previous run

---

AndroidRunner/Plugins/trepn/README.md
AndroidRunner/Plugins/trepn/Trepn.py
examples/native/config.json
examples/web/config.json

This commit extends the overriding logic of Trepn preferences into a self-contained function, allowing users to override all configurations. Mirror the preferences key in the user-defined configuration to extend the overriding to any preference. To reduce the verbosity of the key, the mirrored key contains only the substring after the last dot. For instance, the preference `com.quicinc.preferences.general.profiling_interval` is mapped into `profiling_interval`.

Simplify the overriding of Trepn preferences

---

tests/unit/fixtures/test_config.json
tests/unit/fixtures/test_progress.xml
tests/unit/test_plugins.py
tests/unit/test_progress.py

PR S2-group/android-runner#34 updates the Trepn profiler and allows overriding any preference. This caused a unit test to break as the PR updates the configuration file and replaces `sample_interval` attribute by a map of preferences. This should have been notified in the PR itself.

Fixes a failing test on the Trepn profiler preferences

---

CONTRIBUTING.md

Added instructions to the quick start section (CONTRIBUTING.md) for Mac OS. 
Preview can be found here: 
https://github.com/bommels/android-runner/blob/mac_instructions/CONTRIBUTING.md#setting-up-environment-and-dependencies

Added Mac OS quickstart instructions

---

examples/trepn/Scripts/aggregate_trepn.py

While running on Python 3.8.2 coming with Ubunutu 20.04, I got the following error:
```
root: ScriptError: Error in aggregate_trepn.py: iterator should return strings, not bytes (did you open the file in text mode?)
Traceback (most recent call last):
File "android-runner/AndroidRunner/Script.py", line 33, in mp_run
output = self.execute_script(device, *args, **kwargs)
File "android-runner/AndroidRunner/Python3.py", line 19, in execute_script
return self.module.main(device, *args, **kwargs)
File "/home/milica/android-runner/examples/trepn/Scripts/aggregate_trepn.py", line 79, in main
rows = aggregate(data_dir)
File "/home/milica/android-runner/examples/trepn/Scripts/aggregate_trepn.py", line 64, in aggregate
row.update(aggregate_trepn_final(os.path.join(browser_dir, 'trepn')))
File …
```

text mode for csv.DictReader

---

AndroidRunner/Adb.py
tests/unit/test_devices.py

Add support for installing native apps that have .xapk extension.
Currently only support for .xapk's that only have multiple .apk files in it.
No support yet for the other variant with .xapk's that have a .obb file in it.
Supply path of xapk to paths in the JSON config.
Example config: 
`"paths": [
"android-runner/experiments/apps/com.alibaba.aliexpresshd.xapk",
"android-runner/experiments/apps/com.deliveroo.orderapp.xapk",
"android-runner/experiments/apps/com.reddit.frontpage.xapk",
"android-runner/experiments/apps/com.google.android.youtube.xapk",
"android-runner/experiments/apps/com.ninegag.android.app.apk",
"android-runner/experiments/apps/com.weather.Weather.apk",
"android-runner/experiments/apps/com.inditex.zara.apk"
],`

add xapk (multiple apk files) install feature

---

CONTRIBUTING.md

As of Ubuntu 20.04 the `monkeyrunner` package is not available as a package in the Ubuntu package repository, see here: https://packages.ubuntu.com/search?keywords=monkeyrunner&searchon=names&suite=focal&section=all
There is a package in Ubuntu 20.04 called `android-sdk`. However, this package does also NOT include the monkeyrunner tool.
The easiest way to get monkeyrunner (and ADB as well) on Ubuntu 20.04 is to install Android Studio and change your .bashrc/.zshrc file accordingly so you can access these tools directly from your shell.

Added Ubuntu 20.04 Install instructions (monkeyrunner fix)

---

README.md

Added table to README.md which gives an overview of tested devices and whether there are any known issues. 
For example, the BatteryStats plugin requires the disassembly of the retrieved framework-res.apk using APKTool. However, this can be a problem with devices from specific OEMs as they introduce their own qualifiers and thus breaking the AOSP which APKTools follows. The APKTool creators are thinking of creating a plugin system to handle these custom qualifiers but there is no ETA yet. See here for more: https://github.com/iBotPeaches/Apktool/issues/1420/. So on some devices using the BatteryStats plugin will be difficult.

Added compatible devices table

---

tests/unit/test_devices.py

The merge of pull request #58 introduced a failing test. Test was fixed using tmpdir to mock the filesystem as recommended here https://github.com/S2-group/android-runner/pull/58#issuecomment-724963457.
Also another test was added to check if the function works as expected when an empty xapk is provided.

Fixed tests for #58: install multiple apks using xapk

---

AndroidRunner/Device.py
tests/unit/test_devices.py

Pull request #57 broke tests as it introduces a new way to get the current activity. Instead of extracting the activity data in Python using regular expressions it delegates it to the command line utilities `grep` and `cut`:
Old way:
https://github.com/S2-group/android-runner/blob/a0c1ed1faa0b1e28fc52cc89c8853e60bbf518b9/AndroidRunner/Device.py#L122-L150
New way: 
https://github.com/S2-group/android-runner/blob/e7f402b2ca6819cfd167691c780b80adf8c93044/AndroidRunner/Device.py#L122-L132
Since the data extraction is now delegated to grep and cut it is difficult to employ the same tests. For now I've just deleted most of them.

Fix failing tests for current_activity function.

---

AndroidRunner/Device.py
AndroidRunner/Experiment.py
README.md
tests/unit/test_devices.py

This PR enables users to set the logcat buffer size through the configuration file.  If the user does not provide the logcat_buffer_size, the default value of 128MB is used. Aims to fix #42.

#42 Enables users to set Logcat buffer size through config file

---

AndroidRunner/Plugins/trepn/Trepn.py
AndroidRunner/util.py
tests/unit/test_plugins.py
tests/unit/test_utils.py

The problem described in #41 was caused by the fact that converting the Trepn database to a csv file and moving that csv file to the host takes time. However, the functions doing these actions are non-blocking and thus the flow of the program just continues even if the conversion and moving is not finished.
To fix this issue we now wait till the required files are successfully created and moved before the program flow continues.

Fixes #41 file not found error when using Trepn.

---

AndroidRunner/Adb.py
tests/unit/test_devices.py

Fixes issue #39 by using grep for regular expression instead of the logcat command with the -e flag. The -e flag is not supported on all mobile devices. Using grep solves this problem provided that the host has grep installed. Fortunately, grep is available on nearly all *nix systems and if not, can be easily installed.

Fixed logcat -e regex issue #39 by using grep. 

---

AndroidRunner/Experiment.py
AndroidRunner/NativeExperiment.py
AndroidRunner/PrematureStoppableRun.py
AndroidRunner/StopRunWebserver.py
AndroidRunner/WebExperiment.py
AndroidRunner/util.py
README.md
devices.json
tests/unit/test_experiment.py
tests/unit/test_scripts.py
tests/unit/test_utils.py

Provided AR with run_stopping_condition option in config which supports 3 events:
- logcat_regex: stops the run when a regex is matched in the device's logcat.
- post_request: stops the run when a HTTP POST request is received at the local webserver
- function: stops the run when the stop() function is called on the Experiment instance.
This commit includes:
- Code
- README.md additions
- Tests

Implemented the run_stopping_condition functionality.

---

AndroidRunner/Experiment.py
AndroidRunner/USBHandler.py
AndroidRunner/WebExperiment.py
README.md
tests/unit/test_utils.py

This adds the usb_handler option in the configuration. This makes it possible to programmatically disable the USB charging/power before a run and enable it afterwards.
This commit includes:
- Code
- Tests
- README.md updates

programmatically disable USB charging before run and enable it afterwards

---

AndroidRunner/Plugins/trepn/Trepn.py

When Trepn is used and the device is connected to ADB through WiFi it would be impossible for Trepn to convert the profiling database to a .csv file resulting in a TimeoutError (since it cannot find the csv file within a given time period).
The cause was that the .csv filename was generated based upon the device.id which contains characters that are not valid in filenames. AndroidRunner.util.slugify was used to convert device.id to valid filename.

Fix for Trepn not working when connected to ADB through WiFi

---

AndroidRunner/Plugins/batterystats/Batterystats.py
tests/unit/test_plugins.py

The Batterystats plugin did NOT really stop the profiler when stop_profiling was called which could be a problem when using the stop_running_condition option. This fix solves this problem by running systrace without the -t flag in another thread. Top stop systrace we send a newline to its stdinput.
Commit includes:
- Code
- Tests

Make it possible to stop BatteryStats fully by calling stop_profiling

---

AndroidRunner/Plugins/monsoon/Monsoon.py

When aggregating the data for a subject the code loops over the gathered data files in the directory for each run and puts them in the aggregate file. However, the os.listdir functions returns these files in random order thus making the Monsoon measurement output seem random as well. To fix this problem we sort the os.listdir before looping over its items.

Solves issue of monsoon results being ordered randomly

---

docs/rpi_ar_setup.md

Contains a guide how you can setup AR on a RPi. Shows how to install and configure the Raspberry Pi OS, the required software as well as how to make the (micro) SD-card, used by the RPi as non-volatile memory, read only to prevent SD card corruption. In addition it shows how to configure an external disk which you can use for your data and some general tips & tricks.

Added doc on how to setup AR on the RPi

---

AndroidRunner/Experiment.py
AndroidRunner/WebExperiment.py
tests/unit/test_experiment.py

When terminating a process when using the run_stopping_condition functionality in some cases the queue can get corrupted. This PR fixes this issue. Also includes the corresponding tests.

Fix for problem with Queue of run_stop_condition

---

AndroidRunner/StopRunWebserver.py

Adds the access-control-allow-origin header to the local webserver to prevent CORS warnings in some browsers when sending a HTTP POST request.

Added access-control-allow-origin header to prevent CORS warnings in browser.

---

AndroidRunner/Experiment.py
AndroidRunner/Plugins/batterystats/Batterystats.py
AndroidRunner/WebExperiment.py
tests/unit/test_experiment.py
tests/unit/test_plugins.py

1. Fixes error:
```log
File "android-runner/AndroidRunner/Plugins/batterystats/Batterystats.py", line 165, in collect_results
batterystats_results = self.get_batterystats_results(device)
File "android-runner/AndroidRunner/Plugins/batterystats/Batterystats.py", line 116, in get_batterystats_results
batterystats_results = BatterystatsParser.parse_batterystats(app, batterystats_file, self.powerprofile)
File "android-runner/AndroidRunner/Plugins/batterystats/BatterystatsParser.py", line 81, in parse_batterystats
app_start_time = convert_to_s(re.findall(app_pattern, f)[0][0])
IndexError: list index out of range
```
2. Increased ring buffer size of ftrace. Should reduce the frequncy of th error traces:
```log
File "android-runner/AndroidRunner/Plugins/batterystats/BatterystatsParser.py", line …
```

batterystats fixes

---

CONTRIBUTING.md

Added instructions for installing adb and monkeyrunner on Ubuntu 22.04 command line only. This is helpful for environments without graphical interface where android studio cannot be installed like WSL and docker (although there may be more steps for WSL). Nevertheless, these instructions install the necessary packages to use android runner on Ubuntu 22.04 without having to install Android Studio.

Add command line only instructions for Ubuntu 22.04
